---
language: python
services: docker

env:
  matrix:
    - MOLECULE_DISTRO: centos7
    - MOLECULE_DISTRO: centos6
    - MOLECULE_DISTRO: ubuntu1804
    - MOLECULE_DISTRO: ubuntu1604
    - MOLECULE_DISTRO: debian9
    # disabled due to issue with apt sources in base image
    # - MOLECULE_DISTRO: debian8

install:
  - pip install molecule docker

script:
  - molecule test
